### ISSUE TITLE
崩溃报错

### ISSUE THREAD

**Issue by billdizl** [maning0303/MNMLKitScanner#4]
原因可能在于我引用了一个第三方库也包含camera-camera2:
报错信息如下
java.lang.IllegalStateException: CameraX is not configured properly. The most likely cause is you did not include a default implementation in your build such as 'camera-camera2'.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2670)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1482)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6161)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:892)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
     Caused by: java.lang.IllegalStateException: CameraX is not configured properly. The most likely cause is you did not include a default implementation in your build such as 'camera-camera2'.
        at androidx.camera.core.CameraX.getOrCreateInstance(CameraX.java:360)
        at androidx.camera.lifecycle.ProcessCameraProvider.getInstance(ProcessCameraProvider.java:154)
        at com.maning.mlkitscanner.scan.camera.CameraManager.startCamera(CameraManager.java:91)
        at com.maning.mlkitscanner.scan.ui.ScanPreviewActivity.startCamera(ScanPreviewActivity.java:129)
        at com.maning.mlkitscanner.scan.ui.ScanPreviewActivity.initPermission(ScanPreviewActivity.java:106)
        at com.maning.mlkitscanner.scan.ui.ScanPreviewActivity.onCreate(ScanPreviewActivity.java:73)
        at android.app.Activity.performCreate(Activity.java:6698)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)

**Comment by shuaisong** [comment]
怎么解决的？
