### ISSUE TITLE
17.0.2版本 ML Kit 扫描后崩溃

### ISSUE THREAD

**Issue by yuyuko233** [maning0303/MNMLKitScanner#6]
17.0.2版本的`Barcode`已经移到`com.google.mlkit.vision.barcode.common.Barcode`

MLKit版本

`com.google.mlkit:barcode-scanning:17.0.2`

相关包
```
    def camerax_version = "1.2.0-alpha02"
    implementation "androidx.camera:camera-core:${camerax_version}"
    implementation "androidx.camera:camera-camera2:${camerax_version}"
    implementation "androidx.camera:camera-lifecycle:${camerax_version}"
    implementation "androidx.camera:camera-view:${camerax_version}"

    implementation 'com.google.mlkit:barcode-scanning:17.0.2'
    implementation 'com.github.maning0303:MNMLKitScanner:V1.0.1'
```

报错内容

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.yuyuko233.notificationsynchelper, PID: 18851
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/mlkit/vision/barcode/Barcode;
        at com.maning.mlkitscanner.scan.analyser.BarcodeAnalyser$3.onSuccess(BarcodeAnalyser.java:107)
        at com.maning.mlkitscanner.scan.analyser.BarcodeAnalyser$3.onSuccess(BarcodeAnalyser.java:97)
        at com.google.android.gms.tasks.zzm.run(com.google.android.gms:play-services-tasks@@18.0.1:1)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:8168)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.mlkit.vision.barcode.Barcode" on path: DexPathList[[zip file "/data/app/~~elKMI1T8tIEHWdKbA1fPgg==/com.yuyuko233.notificationsynchelper-CcEORu9cUdfXuElgDSDkyw==/base.apk"],nativeLibraryDirectories=[/data/app/~~elKMI1T8tIEHWdKbA1fPgg==/com.yuyuko233.notificationsynchelper-CcEORu9cUdfXuElgDSDkyw==/lib/arm64, /data/app/~~elKMI1T8tIEHWdKbA1fPgg==/com.yuyuko233.notificationsynchelper-CcEORu9cUdfXuElgDSDkyw==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.maning.mlkitscanner.scan.analyser.BarcodeAnalyser$3.onSuccess(BarcodeAnalyser.java:107) 
        at com.maning.mlkitscanner.scan.analyser.BarcodeAnalyser$3.onSuccess(BarcodeAnalyser.java:97) 
        at com.google.android.gms.tasks.zzm.run(com.google.android.gms:play-services-tasks@@18.0.1:1) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:236) 
        at android.app.ActivityThread.main(ActivityThread.java:8168) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967) 
```

**Comment by maning0303** [comment]
17.0.2版本Barcode 路径修改，所以报错，后续我会把版本升级到17.0.2，感谢反馈

**Comment by maning0303** [comment]
最新版本已修复
